export const skills = [
    "HTML",
    "CSS",
    "Tailwind Css",
    "JavaScript",
    "TypeScript",
    "React",
    "React Native",
    "Flutter",
    "NextJs 13",
    "Redux",
    "Redux Toolkit",
    "Firebase",
    "NodeJs",
    "ExpressJs",
    "MongoDB",
    "MySQL",
    "Prisma",
    "Socket io"
]